/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiKlinesRouteImport } from './routes/api/klines'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as ApiPublicHooksCheckAlertsRouteImport } from './routes/api/public/hooks/check-alerts'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKlinesRoute = ApiKlinesRouteImport.update({
  id: '/api/klines',
  path: '/api/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckAlertsRoute =
  ApiPublicHooksCheckAlertsRouteImport.update({
    id: '/api/public/hooks/check-alerts',
    path: '/api/public/hooks/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/klines': typeof ApiKlinesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/s/$id': typeof SIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/klines': typeof ApiKlinesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/s/$id': typeof SIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/studio': typeof StudioRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/klines': typeof ApiKlinesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/s/$id': typeof SIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/studio'
    | '/api/generate'
    | '/api/klines'
    | '/checkout/return'
    | '/s/$id'
    | '/api/public/hooks/check-alerts'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/studio'
    | '/api/generate'
    | '/api/klines'
    | '/checkout/return'
    | '/s/$id'
    | '/api/public/hooks/check-alerts'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/studio'
    | '/api/generate'
    | '/api/klines'
    | '/checkout/return'
    | '/s/$id'
    | '/api/public/hooks/check-alerts'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  StudioRoute: typeof StudioRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiKlinesRoute: typeof ApiKlinesRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  SIdRoute: typeof SIdRoute
  ApiPublicHooksCheckAlertsRoute: typeof ApiPublicHooksCheckAlertsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/klines': {
      id: '/api/klines'
      path: '/api/klines'
      fullPath: '/api/klines'
      preLoaderRoute: typeof ApiKlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-alerts': {
      id: '/api/public/hooks/check-alerts'
      path: '/api/public/hooks/check-alerts'
      fullPath: '/api/public/hooks/check-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  StudioRoute: StudioRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiKlinesRoute: ApiKlinesRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  SIdRoute: SIdRoute,
  ApiPublicHooksCheckAlertsRoute: ApiPublicHooksCheckAlertsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
